# Stages
# Stage-1:
  # Task-1: Build Docker Image and push to Azure Container Registry ACR
  # Task-2: Copy kube-manifest files to Build Artifact Directory
  # Task-3: Publish build articats to Azure Pipelines
# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3  

trigger:
- main

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Stage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Tarun_Docker'
        repository: 'tarunashwini/flask-webapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/kube-manifests'
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/kube-manifests'
        OverWrite: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/kube-manifests'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'