# Stages
# Stage-1:
  # Task-1: Build Docker Image and push to Azure Container Registry ACR
  # Task-2: Copy kube-manifest files to Build Artifact Directory
  # Task-3: Publish build articats to Azure Pipelines
# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3  

trigger:
- main

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Stage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Listing the contents of the working directory:"
        ls -al $(System.DefaultWorkingDirectory)
        echo "Listing the contents of the kube-manifests directory:"
        ls -al $(System.DefaultWorkingDirectory)/kube-manifests
      displayName: 'List directory contents'

    - task: Docker@2
      inputs:
        containerRegistry: 'Tarun_Docker'
        repository: 'tarunashwini/flask-webapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'
