apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  labels:
    app: python-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: python-webapp-container
        image: tarunr.azurecr.io/flask-webapp
        ports:
        - containerPort: 80

---

apiVersion: v1
  kind: Service
  metadata:
    name: python-webapp
  spec:
    type: LoadBalancer
    selector:
      app: python-webapp
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
